/**
 * Copyright (c) 2020 Mongker.
 * All rights reserved.
 * @author Mongker 20/09/2020
 * @email: levanmong.dola.99@gmail.com
 * @student-code: 68DCHT20091
 * @university: UTT (Đại học Công Nghệ Giao Thông Vận Tải)
 */

export const SLIDER = {
    GET_LIST: 'GET_LIST',
    POST_SLIDER: 'POST_SLIDER',
    DELETE: 'DELETE',
    PUT: 'PUT',

    CALL_DELETE: 'CAL_DELETE',
    CALL_GET_LIST: 'CALL_GET_LIST',
    CALL_POST_SLIDER: 'CALL_POST_SLIDER',
    CALL_PUT: 'CALL_PUT',
};
export const CART = {
    GET_LIST: 'GET_LIST_CART',
    POST: 'POST_CART',
    DELETE: 'DELETE_CART',
    PUT: 'PUT_CART',

    CALL_DELETE: 'CAL_DELETE_CART',
    CALL_GET_LIST: 'CALL_GET_LIST_CART',
    CALL_POST: 'CALL_POST_CART',
    CALL_PUT: 'CALL_PUT_CART',
};

export const ADMIN = {
    GET_LIST: 'GET_LIST_ADMIN',
    POST_ADMIN: 'POST_ADMIN',
    DELETE: 'DELETE_ADMIN',
    PUT: 'PUT_ADMIN',
    LOGIN: 'LOGIN_ADMIN',
    GET_ADMIN: 'GET_ADMIN_ID',
    GET_ADMIN_DATA: 'GET_ADMIN_ID_DATA',

    CALL_DELETE: 'CAL_DELETE_ADMIN',
    CALL_GET_LIST: 'CALL_GET_LIST_ADMIN',
    CALL_POST_ADMIN: 'CALL_POST_ADMIN',
    CALL_PUT: 'CALL_PUT_ADMIN',
};

export const USER = {
    GET_LIST: 'GET_LIST_USER',
    POST_ADMIN: 'POST_USER',
    DELETE: 'DELETE_USER',
    PUT: 'PUT_USER',
    GET_ADMIN: 'GET_USER_ID',
    GET_ADMIN_DATA: 'GET_USER_ID_DATA',
    LOGIN: 'LOGIN',

    CALL_LOGIN: 'CALL_LOGIN_USER',
    CALL_DELETE: 'CAL_DELETE_USER',
    CALL_GET_LIST: 'CALL_GET_LIST_USER',
    CALL_POST_ADMIN: 'CALL_POST_USER',
    CALL_PUT: 'CALL_PUT_USER',
};

export const CATALOG = {
    GET_LIST: 'GET_LIST_CATALOG',
    POST: 'POST_CATALOG',
    DELETE: 'DELETE_CATALOG',
    PUT: 'PUT_CATALOG',

    CALL_DELETE: 'CAL_DELETE_CATALOG',
    CALL_GET_LIST: 'CALL_GET_LIST_CATALOG',
    CALL_POST: 'CALL_POST_CATALOG',
    CALL_PUT: 'CALL_PUT_CATALOG',
};

export const PRODUCT = {
    GET_LIST_ID_CATALOG: 'GET_LIST_ID_CATALOG',
    GET_LIST: 'GET_LIST_PRODUCT',
    POST: 'POST_PRODUCT',
    DELETE: 'DELETE_PRODUCT',
    PUT: 'PUT_PRODUCT',

    CALL_GET_LIST_ID_CATALOG: 'CALL_GET_LIST_ID_CATALOG',
    CALL_GET_LIST: 'CALL_GET_LIST_PRODUCT',
};
